declare module 'react-feather/dist/icons/book';
declare module 'react-feather/dist/icons/codepen';
declare module 'react-feather/dist/icons/github';
declare module 'react-feather/dist/icons/home';
declare module 'react-feather/dist/icons/instagram';
declare module 'react-feather/dist/icons/linkedin';
declare module 'react-feather/dist/icons/mail';
declare module 'react-feather/dist/icons/twitter';
declare module 'react-feather/dist/icons/user';
